---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-frontend-hpa
  namespace: mycart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myacart-frontend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70